### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tegk**
I did some "clean up" and minor refactoring :-)

snake_case is not preferred in Go btw

### CODE REVIEW

**Comment by geohot** [comment]
I sort of refuse to do the 8 spaces, even though it's the Go standard, I find it unreadable.

**Comment by atsman** [comment]
Shouldn't it just be tab characters by standard? Then you can redefine tab to whatever number of spaces you want

```
setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4
```

**Comment by tegk** [comment]
It's tabs indeed

**Comment by tegk** [comment]
@geohot  Mr. Hotz, shall I still replace tabs with 4 spaces?

**Comment by geohot** [comment]
Let's leave it two spaces.

**Comment by tegk** [comment]
yea, thanks. Please open it again and I reformat with two spaces :-)

**Pull request closed without merging**
