### PR TITLE
Simplify error creation with `fmt.Errorf`

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/minikeyvalue/issues/?category=recommended). This PR fixes a few of them.

### Summary of fixes
- Simplify error creation with `fmt.Errorf`
- added .deepsource.toml fle

### CODE REVIEW

**Comment by withshubh** [comment]
@geohot :wave: 

Please review the PR! :sparkles:

**Comment by bdkiran** [comment]
@withshubh I know you're trying to promote your analysis tool, but this seems like a pretty lame way to go about it....

**Comment by withshubh** [comment]
@bdkiran :wave: 
I would really appreciate it if you could drop any suggestion on what I can do to onboard you (or minikeyvalue) on DeepSource.

**Comment by geohot** [comment]
Can you submit this without changing the formatting?

**Comment by withshubh** [comment]
> Can you submit this without changing the formatting?

You mean just the `.deepsource.toml` file?

**Pull request closed without merging**
